import { NextPage } from "next";
import Head from "next/head"

const SimpleSearch: NextPage = ({handleChange, setComplexSearchVisibility}) => {
    return (
    <>
        <Head>
            <title>Simple Search</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="main-page">
            {/* <video autoplay loop src="https://www.youtube.com/watch?v=827QFRWNgFw"></video> */}
            <div className="search-container">
                <div className="search-container">
                    <h1>Find your dish!</h1>
                    <input type="text" placeholder="Search for your recipe here!" onChange={handleChange} />
                    <div className="btn-container">
                        <button onClick={() => handleSearch(formState.search)}>Search!</button>
                        <button onClick={() => setComplexSearchVisibility(true)}>Expanded Search</button>
                    </div>
                </div>
            </div>
        </main>
        <style jsx>{`
            .main-page {
                position: relative;
                height: 100vh;
                width: 100vw;
                display: flex;
                justify-content: center;
                align-items: center;
                background-image: url("https://rare-gallery.com/uploads/posts/585465-board-bunch.jpg");
                background-position: center;
                background-size: cover;
                background-repeat: no-repeat;
            }
        
            .background-video {
                height: 100%;
                width: 100%;
                position: absolute;
                top: 0;
                left: 0
            }
        
            .search-container {
                width: 750px;
                display: flex;
                justify-content: center;
                align-items: center;
                display: flex;
                flex-direction: column;
                justify-content: center;
                align-items: center
            }
        
            .search-container h1 {
                font-size: 2rem;
                font-weight: bold;
                animation: animate 0.5s linear
            }
        
            .search-container input {
                width: 100%;
                height: 40px;
                border: none;
                border-radius: 5px;
                padding: 5px;
                animation: animate 0.5s linear;
                animation-delay: 0.25s
            }

            .btn-container {
                margin-top: 10px
            }
        
            .search-container button {
                margin-top: 10px;
                border: none;
                padding: 10px;
                border-radius: 5px;
                background: #1DA1F2;
                font-weight: bold;
                color: white;
                cursor: pointer;
                transition: 0.25s linear;
                margin: 5px
            }
        
            .search-container button:hover {
                color: gold
            } 
        
            @keyframes animate {
                0% {
                    opacity: 0;
                    transform: translateY(50%);
                }
        
                100% {
                    opacity: 1;
                    transform: translateY(0);
                }
            }
        `}</style>
    </>
    )
}

export default SimpleSearch